<?php
/**
 * Created by PhpStorm.
 * User: l.gang06@yahoo.com
 * Date: 2017/6/1
 * Time: 15:38
 */

namespace Externalapi\Rpcapi\Push;
use Rpc\RpchttpModel;
use Api\Globals\Functions;
class SubscriptionModel extends RpchttpModel
{
    /**
     * @param array $params
     * @desc
     *    $params
     *      暂时提供方法 建议直接使用对应方法
     *          查询信息接口 对应 uninfo 方法
     *              $params = [
     *                  'mod' => 'td' #固定
     *                  '@reqtype' => '/interface/main.php', #固定
     *                  'userid' => 根据实际传入用户id
     *              ]
     *          订阅与退订 对应 td 方法
     *               $params = [
     *                  '@reqtype' => 'td', #固定
     *                  'userid' => 根据实际传入用户id
     *                  'type' => add|del
     *                  'cate' => 栏目id
     *              ]
     *          查询栏目对应关系 对应 columnsList
     *              $params['mod'] = 'td';
                    $params['req'] = 'getList';
                    $params['appid'] = $appid;
                    $params['@reqtype'] = '/interface/main.php';
     * @return \Rpc\json
     */
    public function send($params = array())
    {
        $params = Functions::apiParamsCheck($params);
        $this->_methodType = "GET";
        if (isset($params['@reqtype'])) {
            $params['@reqtype']  = rtrim($params['@reqtype'], '/');
        }
        return parent::send($params); // TODO: Change the autogenerated stub
    }

    /**
     *
     * @params string $userId
     * @desc
     *   用户退订信息查询
     */
    public function uninfo($userId)
    {
        $params['mod'] = 'td';
        $params['userid'] = $userId;
        $params['@reqtype'] = '/interface/main.php';
        return $this->send($params);
    }

    /**
     * 栏目列表默认appid=2
     */

    public function columnsList($appid = 2)
    {
        $params['mod'] = 'td';
        $params['req'] = 'getList';
        $params['appid'] = $appid;
        $params['@reqtype'] = '/interface/main.php';
        return $this->send($params);
    }

    /**
     * @param array $parmas
     *    userid:
     *    cate: 退订栏目id
     *    type: del|add
     */
    public function unsubscribe($params = array())
    {
        $params = Functions::apiParamsCheck($params);
        $params['@reqtype'] = 'td';
        return parent::send($params);
    }



    protected function _errorCodeKeyMap()
    {
        return 'code';
    }

    protected function _errorCodeSuccessVal()
    {
        return 0;
    }

    protected function _errorMsgKeyMap()
    {
        return '';
    }

    protected function _resultDataMap()
    {
        return '';
    }


}