<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查看详情</title>
    <link rel="stylesheet" href="/js/layui/css/layui.css">
    <style>
        .content{
            width: 100%;
        }
        .menu {
            width: 100%;
            height: 50px;
            text-align: center;
        }
    </style>
</head>
<body>
<fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
    <legend>
        日志明细
    </legend>
</fieldset>

<div id="content" class="content">
    <div class="layui-form">
        <table class="layui-table">
            <colgroup>
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="80">
            </colgroup>
            <thead>
                <tr>
                    <th>时间</th>
                    <th>日志级别</th>
                    <th>服务名称</th>
                    <th>服务url</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="tbody">
<!--                <tr>-->
<!--                    <td>2011-11-11 00:11:22</td>-->
<!--                    <td>NOTICE</td>-->
<!--                    <td>I问财openapi平台</td>-->
<!--                    <td>http://10.0.34.204:801/search/v1/spell</td>-->
<!--                    <td><button class="layui-btn layui-btn-small" onclick="viewDetail()">查看详情</button></td>-->
<!--                </tr>-->
            </tbody>
        </table>
</div>
    <div class="menu">
        <div id="detail"></div>
    </div>
    <div id="type" style="display: none;"><?= $type?></div>
    <div id="startDate" style="display: none;"><?= $startDate?></div>
    <div id="endDate" style="display: none;"><?= $endDate?></div>
    <div id="ip" style="display: none;"><?= $ip?></div>
    <div id="url" style="display: none;"><?= $url?></div>
    <div id="appid" style="display: none;"><?= $appid?></div>
<script src="/js/layui/layui.js"></script>
<script>
    var index= 0;
    var size = 50;
    layui.use(['laypage', 'layer', 'jquery'], function () {
        var type = layui.jquery('#type').html();
        layer = layui.layer;
        laypage = layui.laypage;
        layer.load(1);
        layui.jquery.ajax({
            url: '/log/index/querydetail',
            type: 'POST',
            dataType: 'json',
            data: {
                type:type,
                startDate: layui.jquery('#startDate').html(),
                endDate: layui.jquery('#endDate').html(),
                ip: layui.jquery('#ip').html(),
                url: layui.jquery('#url').html(),
                appid: layui.jquery('#appid').html(),
            },
            success: function(data) {
                var datas = data.result;
//                alert(JSON.stringify(datas));
                var nums = 10;//出现的数据量
                var render = function(data, curr) {
                    var arr = [];
                    var thisData = data.concat().splice(curr*nums - nums, nums);
                    layui.each(thisData, function(index, item){
                       arr.push("<tr>"
                           +"<td>"+item.datetime+"</td>"
                           +"<td>"+getLogLevel(item.errorlevel)+"</td>"
                           +"<td>"+item.servicename+"</td>"
                           +"<td>"+getUrl(item)+"</td>"
                           +"<td><button class=\"layui-btn layui-btn-small\" onclick=\"viewDetail("+item.id+")\">查看详情</button></td>"
                           +"</tr>");
                    });
                    return arr.join('');
                }
                laypage({
                    cont: 'detail',
                    pages: Math.ceil(datas.length / nums),
                    jump: function(obj) {
                        document.getElementById('tbody').innerHTML = render(datas, obj.curr);
                    }
                });
                setTimeout(function(){
                   layer.closeAll('loading');
                }, 0);
            }
        });
    });

    function getUrl(item) {
        if(item.serviceurl != 'null') {
            return item.serviceurl;
        }
        if(item.url != 'null') {
            return item.url;
        }
        return '无';
    }

    function getLogLevel(index) {
        var level = ['TRACE','INFO', 'NOTICE', 'WARN', 'ERROR'];
        return level[index];
    }

    var base64DecodeChars = new Array(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, 63, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, -1, -1, -1, -1, -1, -1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, -1, -1, -1, -1, -1, -1, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, -1, -1, -1, -1, -1);
    function base64decode(str) {
        var c1, c2, c3, c4;
        var i, len, out;
        len = str.length;
        i = 0;
        out = "";
        while (i < len) {
            do {
                c1 = base64DecodeChars[str.charCodeAt(i++) & 0xff];
            } while (i < len && c1 == -1);
            if (c1 == -1)           break;
            do {
                c2 = base64DecodeChars[str.charCodeAt(i++) & 0xff];
            } while (i < len && c2 == -1);
            if (c2 == -1)           break;
            out += String.fromCharCode((c1 << 2) | ((c2 & 0x30) >> 4));
            do {
                c3 = str.charCodeAt(i++) & 0xff;
                if (c3 == 61)           return out;
                c3 = base64DecodeChars[c3];
            } while (i < len && c3 == -1);
            if (c3 == -1)           break;
            out += String.fromCharCode(((c2 & 0XF) << 4) | ((c3 & 0x3C) >> 2));
            do {
                c4 = str.charCodeAt(i++) & 0xff;
                if (c4 == 61)            return out;
                c4 = base64DecodeChars[c4];
            } while (i < len && c4 == -1);
            if (c4 == -1)            break;
            out += String.fromCharCode(((c3 & 0x03) << 6) | c4);
        }
        return out;
    }
    function viewDetail(logId)
    {
        layer.open({
            type: 2,
            title: '日志明细查看',
            shadeClose: true,
            maxmin: true,
            area: ['90%', '98%'],
            content: '/log/index/servicelogdetail?logId='+logId
        });
    }
</script>
</body>
</html>