<html>
<head>
    <link rel="stylesheet" href="/js/layui/css/layui.css">
</head>
<body>
<script src="http://s.thsi.cn/cb?js/;jquery-1.8.3.min.js"></script>
<script src="/js/layui/layui.js"></script>


<fieldset class="layui-elem-field layui-field-title" style="margin-top:20px">
    <legend>Debug调试Demo</legend>
</fieldset>
<ul class="layui-nav" lay-filter="admin-nav">
    <li class="layui-nav-item"><a href="<?php echo $this->baseUrl?>/service/index">服务列表</a></li>
    <li class="layui-nav-item"><a href="<?php echo $this->baseUrl?>/apps/index">应用列表</a></li>
    <li class="layui-nav-item"><a href="<?php echo $this->baseUrl?>/apps/applylist">申请应用</a></li>
    <li class="layui-nav-item"><a href="<?php echo $this->baseUrl?>/router/list">路由映射</a></li>
    <li class="layui-nav-item">
        <a href="javascript:;">缓存</a>
        <dl class="layui-nav-child">
            <dd><a href="<?php echo $this->baseUrl?>/stats/rediskey">redis缓存</a></dd>
        </dl>
    </li>
</ul>
<hr>
<font color="red">
<?php echo isset($this->errorMsg) ?  $this->errorMsg: '';?>
</font>
<script>
    layui.use('element', function(){
        var element = layui.element();
//        element.on('nav(admin-nav)', function(ele){
//
//        })
    })
</script>