<?php
require dirname(__FILE__) . '/../menu.phtml';
?>
<fieldset class="layui-elem-field layui-field-title" style="margin-top:20px">
    <legend>redis key列表</legend>
</fieldset>
<form class="layui-form" method="get">
    <div class="layui-form-item">
        <label class="layui-form-label">应用ID:</label>
        <div class="layui-input-inline">
            <input type="text" value="<?php echo $this->appid;?>" name="appid"  class="layui-input" lay-filter="url">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">key前缀:</label>
        <div class="layui-input-inline">
            <input type="text" value="<?php echo $this->key;?>" name="key"  class="layui-input" lay-filter="url" >
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label"></label>
        <div class="layui-input-inline">
            <button lay-submit class="layui-btn" lay-filter="submit">提交</button>
        </div>
    </div>
</form>
<table class="layui-table" style="width:200px;">
    <tr>
        <td>总计</td>
        <td><?php echo $this->list['total'];?></td>
    </tr>
</table>
<fieldset class="layui-elem-field layui-field-title" style="margin-top:20px">
    <legend>最近到期部分key列表</legend>
</fieldset>
<table class="layui-table">
    <thead>
    <tr>
        <td>应用ID</td>
        <td>key</td>
        <td>缓存创建时间</td>
        <td>到期时间</td>
    </tr>
    </thead>
    <?php foreach ($this->list['data'] as $item):?>
        <tr>
            <td><?php echo $item->app;?></td>
            <td><?php echo $item->cachekey;?></td>
            <td><?php echo $item->cachecreate;?></td>
            <td><?php echo $item->expire;?></td>
        </tr>
    <?php endforeach;
    ?>
</table>

<div id="paginator"></div>
<script>
    layui.use(['laypage'], function () {
        var laypage = layui.laypage;
        laypage({
            cont : document.getElementById('paginator'),
            pages : <?php echo $this->list['totalPage'];?>,
           //groups: 10,
            skip:true,
            jump:function(obj) {
                console.log(obj);
            }
        })

    })

    var render = function (data, curr)
    {
        alert(data);
    }

</script>