<?php
/**
 * Created by PhpStorm.
 * User: l.gang06@yahoo.com
 * Date: 2017/4/25
 * Time: 10:59
 */
namespace Externalapi\Rpcapi;
use Rpc\RpchttpModel;
use Api\Globals\Functions;
class CircleModel extends RpchttpModel
{
    /**
     * @param array $params
     * @desc 参考圈子wiki中的具体接口参数说明
     *      其中用户登录的认证
     *          @cookie 通过http header方式传递
     *          cookie 接口自定义协议, 支持数组与字符串
     *
     * @return \Rpc\json|\Rpc\xml
     */
    public function send($params = array())
    {
        $params = Functions::apiParamsCheck($params);
        if (isset($params['cookie']) && is_array($params['cookie'])) {
            $params['cookie'] = Functions::cookieToString($params['cookie']);
        }
        return parent::send($params); // TODO: Change the autogenerated stub
    }

    protected function _errorCodeKeyMap()
    {
        return 'errorCode';
    }

    protected function _errorCodeSuccessVal()
    {
        return 0;
    }

    protected function _errorMsgKeyMap()
    {
        return 'errorMsg';
    }

    protected function _resultDataMap()
    {
        return 'result';
    }


}
