<html>
<head>
    <link rel="stylesheet" href="/js/layui/css/layui.css">
    <link rel="stylesheet" href="/js/jsonview/jsonview.css">
</head>
<body>
<script src="http://s.thsi.cn/cb?js/;jquery-1.8.3.min.js"></script>
<script src="/js/layui/layui.js"></script>
<script src="/js/jsonview/jsonview.js"></script>
<fieldset class="layui-elem-field layui-field-title" style="margin-top:20px">
    <legend>Debug调试Demo</legend>
</fieldset>
<div class="layui-elem-quote">
    <div>调用demo</div>
    <div><?php echo $this->demoStr;?></div>
</div>
<blockquote class="layui-elem-quote">
返回结果
<div id="json">

</div>


</blockquote>


<script>
    $('#json').JSONView(<?php echo json_encode($this->result);?>)
</script>


</body>

</html>