<?php
require dirname(__FILE__) . '/../menu.phtml';
?>
<fieldset class="layui-elem-field layui-field-title" style="margin-top:20px">
    <legend>添加服务权限</legend>
</fieldset>
<form method="post">
    <input type="hidden" value="<?php echo $this->appid;?>" name="appid">
<table class="layui-table">
    <tr>
        <td>应用名称</td>
        <td><?php echo $this->appname;?></td>
    </tr>
    <tr>
        <td>服务</td>
        <td>
            <select name="apiid[]" multiple="multiple" size="20">
                <?php
                    foreach ($this->serviceList as $item):
                ?>
                        <option value="<?php echo $item['id'];?>" <?php if (isset($this->hasService[$item['id']])): echo 'selected'; endif;?>>
                            <?php echo $item['name'];?>
                        </option>
                <?php
                    endforeach;
                ?>
            </select>
        </td>
    </tr>
    <tr>
        <td></td>
        <td><input type="submit" name="submitBut" value="提交"></td>
    </tr>
</table>
</form>