<?php
require dirname(__FILE__) . '/../menu.phtml';
?>
<fieldset class="layui-elem-field layui-field-title" style="margin-top:20px">
    <legend>应用申请</legend>
</fieldset>
<form method="post">
<table class="layui-table">
    <tr>
        <td>应用名</td>
        <td><input type="text" name="appName"></td>
    </tr>
    <tr>
        <td></td>
        <td><input type="submit" name="submitBut" value="提交"></td>
    </tr>
</table>
</form>