<?php
require dirname(__FILE__) . '/../menu.phtml';
?>
<fieldset class="layui-elem-field layui-field-title" style="margin-top:20px">
    <legend>应用列表</legend>
</fieldset>
<table class="layui-table">
    <thead>
    <tr>
        <td>ID</td>
        <td>应用ID</td>
        <td>秘钥</td>
        <td>应用名称</td>
        <td>申请人</td>
        <td>申请日期</td>
        <td>操作</td>
    </tr>
    </thead>
    <?php foreach ($this->list as $item):?>
        <tr>
            <td><?php echo $item['id'];?></td>
            <td><?php echo $item['appid'];?></td>
            <td><?php echo $item['secret'];?></td>
            <td><?php echo $item['appname'];?></td>
            <td><?php echo $item['applyuser'];?></td>
            <td><?php echo $item['applydate'];?></td>
            <td>
                <a href="<?php echo $this->baseUrl;?>/apps/addservice/?appid=<?php echo $item['appid'];?>">添加权限</a>
                / <a href="<?php echo $this->baseUrl;?>/apps/bindthirdauth/?appid=<?php echo $item['appid'];?>">第三方接口认证</a>
            </td>
        </tr>
    <?php endforeach;
    ?>
    <?php
    ?>
</table>
